name: subspace_env_clean
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - ld_impl_linux-64=2.39
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgomp=12.2.0
  - libnsl=2.0.0
  - libsqlite=3.40.0
  - libuuid=2.32.1
  - libzlib=1.2.13
  - ncurses=6.3
  - openssl=3.0.7
  - pip=22.3.1
  - python=3.9.15
  - readline=8.1.2
  - setuptools=66.1.1
  - tk=8.6.12
  - tzdata=2022g
  - wheel=0.38.4
  - xz=5.2.6
  - pip:
    - equinox==0.9.2
    - jax==0.4.1
    - jaxlib==0.4.1
    - jaxtyping==0.2.11
    - libigl==0.0.3
    - numpy==1.24.1
    - opt-einsum==3.3.0
    - polyscope==1.3.1
    - potpourri3d==0.0.8
    - scipy==1.10.0
    - typeguard==2.13.3
    - typing-extensions==4.4.0
